class Strings:  # 类名不要以下划线开头
    test_name = "test_name"
    please_input_your_15 = "Input 15 digital IMEI number"
    copr_tcl_all_rights = "@Copr. 2021 TCL All rights reserved"
    you_must_provide = "You must provide a legal IMEI number"
    digit_imei_is_required = "15 digit IMEI number is required"
    all_operation_are_success = "All operations are successful\nYou can enjoy the internet now."
    unfortunately_the_verification = "Unfortunately, the verification failed!\nYou can plug dongle again and click try again"
    ok = "OK"
    the_current_network = "The current network connection timed out!\nPlease try again"
    try_again = "Try again"
